### ISSUE TITLE
Even if I connect my wallet, I can't log in to "lenster".

### ISSUE THREAD

**Issue by NFTASTE** [lens-protocol/api-examples#127]
I recently bought an NFT from opensea with "@starfalla.lens -Lens profile" Id: #111310
And I'm trying to log in to the wallet with nft in lenster.xyz, but I can't.
I asked Discord and they told me to send it to another wallet and try it again, but I can't. I said no.
They said to just wait. But you can't wait. Please let me do lenster.

Please reply as soon as possible. 
dhgustjr201@naver.com

![렌즈프로토콜](https://user-images.githubusercontent.com/126792257/222454889-b6435814-7cd2-420c-a914-c7aae2d9aba3.jpg)
![렌즈프로토콜2](https://user-images.githubusercontent.com/126792257/222454988-a141f6a9-30a8-45c7-b3ae-278b92e20121.jpg)
![렌즈프로토콜3](https://user-images.githubusercontent.com/126792257/222455039-516c8a1b-d9de-45c5-b0f7-a02305eb9144.jpg)
![렌즈프로토콜4](https://user-images.githubusercontent.com/126792257/222455057-44806051-8eb8-4193-bcc0-4b2ba473c1c0.jpg)

**Comment by juangm** [comment]
Hi, 

I have reviewed your activity on [starfallarena](https://hey.xyz/u/starfallarena) and noted that the most recent post was made on [July 10, 2023](https://hey.xyz/posts/0x01b2ce-0x02d0). It appears that your access is functioning properly, and you have been able to create content successfully.

Based on this information, I am proceeding to close the ticket as the issue seems to have been resolved.
